---
name: "PR: Test docker image (base)"

on:
  pull_request:
    paths:
      - resources/docker/Dockerfile.base

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - run: |
          make "$GITHUB_ENV"

      - name: Build
        uses: nhatthm/gh-actions/docker-build-and-push@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          context: .
          push: false
          file: resources/docker/Dockerfile.base
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
