---
name: "PR: Cleanup"

on:
  pull_request:
    types:
      - closed

env:
  VERSION: PR-${{ github.event.pull_request.number }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Delete release
        uses: ./.github/actions/delete-release
        with:
          release: ${{ env.VERSION }}

  delete-image:
    name: Delete image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete image
        uses: nhatthm/gh-actions/docker-delete-image@master
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          name: ${{ env.IMAGE_NAME }}
          tag: pr-${{ github.event.pull_request.number }}

  delete-notification:
    runs-on: ubuntu-latest
    needs: [delete-image, delete-release]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Delete comment
        uses: nhatthm/gh-actions/github-one-comment@master
        with:
          body-include: "<!-- release-comment -->"
          delete: "true"
