---
name: Release (Stable)

concurrency: "release-stable"

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Find Go version
        uses: nhatthm/gh-actions/find-go-version@master

      - name: Normalize Go version
        run: |
          echo "GO_VERSION=$(echo "$GO_VERSION" | cut -d '.' -f 1-2)" >> "$GITHUB_ENV"

      - run: |
          make "$GITHUB_ENV"

      - name: Build and push
        uses: nhatthm/gh-actions/docker-build-and-push@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          context: .
          push: true
          file: resources/docker/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            VERSION=${{ github.event.release.tag_name }}
            USER=${{ github.actor }}
            REVISION=${{ github.sha }}
